server {
    listen 80;

    server_name anishelf.app www.anishelf.app;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://anishelf.app$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name anishelf.app www.anishelf.app;

    ssl_certificate /etc/letsencrypt/live/anishelf.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/anishelf.app/privkey.pem;

    location /api {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://159.89.116.149:5000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Connection "";
        proxy_http_version 1.1;
    }

    location / {
        proxy_pass http://159.89.116.149:3000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
    }

}
